[2022-01-24 20:01:16,920] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data.load_venv manual__2022-01-24T20:01:13.750109+00:00 [queued]>
[2022-01-24 20:01:16,936] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data.load_venv manual__2022-01-24T20:01:13.750109+00:00 [queued]>
[2022-01-24 20:01:16,936] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-01-24 20:01:16,936] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-01-24 20:01:16,937] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-01-24 20:01:16,949] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): load_venv> on 2022-01-24 20:01:13.750109+00:00
[2022-01-24 20:01:16,958] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'ingest_data', 'load_venv', 'manual__2022-01-24T20:01:13.750109+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/dag_01.py', '--cfg-path', '/tmp/tmpwife92f_', '--error-file', '/tmp/tmpwpn4zea9']
[2022-01-24 20:01:16,959] {standard_task_runner.py:77} INFO - Job 10: Subtask load_venv
[2022-01-24 20:01:16,955] {standard_task_runner.py:52} INFO - Started process 432 to run task
[2022-01-24 20:01:17,021] {logging_mixin.py:109} INFO - Running <TaskInstance: ingest_data.load_venv manual__2022-01-24T20:01:13.750109+00:00 [running]> on host 1aa77c892e3a
[2022-01-24 20:01:17,086] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ingest_data
AIRFLOW_CTX_TASK_ID=load_venv
AIRFLOW_CTX_EXECUTION_DATE=2022-01-24T20:01:13.750109+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-01-24T20:01:13.750109+00:00
[2022-01-24 20:01:17,087] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-01-24 20:01:17,088] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'source venv/bin/activate  && pip install -r requirements.txt']
[2022-01-24 20:01:17,098] {subprocess.py:85} INFO - Output:
[2022-01-24 20:01:17,100] {subprocess.py:89} INFO - bash: venv/bin/activate: No such file or directory
[2022-01-24 20:01:17,101] {subprocess.py:93} INFO - Command exited with return code 1
[2022-01-24 20:01:17,115] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/bash.py", line 188, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2022-01-24 20:01:17,124] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=ingest_data, task_id=load_venv, execution_date=20220124T200113, start_date=20220124T200116, end_date=20220124T200117
[2022-01-24 20:01:17,140] {standard_task_runner.py:92} ERROR - Failed to execute job 10 for task load_venv
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/bash.py", line 188, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2022-01-24 20:01:17,172] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-01-24 20:01:17,220] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
